### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by samIndeed** [aristoteleo/Scribe-py#6]
Hi, when I try to install I get an error. The error below is from a Mac, but on linux I get the same thing (with some different line numbers)

I did a pip install (I fixed a typo and changed a : to a /). So I entered

pip install git+https://github.com/aristoteleo/Scribe-py

and got the output below. Thanks for taking a look!

Collecting git+https://github.com/aristoteleo/Scribe-py
  Cloning https://github.com/aristoteleo/Scribe-py to /private/var/folders/yd/lvv_242j0_j38xt5p54y2q8w0000gn/T/pip-req-build-zoh5p0rp
  Running command git clone -q https://github.com/aristoteleo/Scribe-py /private/var/folders/yd/lvv_242j0_j38xt5p54y2q8w0000gn/T/pip-req-build-zoh5p0rp
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/yd/lvv_242j0_j38xt5p54y2q8w0000gn/T/tmpc8h1o041
         cwd: /private/var/folders/yd/lvv_242j0_j38xt5p54y2q8w0000gn/T/pip-req-build-zoh5p0rp
    Complete output (28 lines):
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/yd/lvv_242j0_j38xt5p54y2q8w0000gn/T/pip-build-env-ys8mlda8/overlay/lib/python3.7/site-packages/flit_core/buildapi.py", line 46, in prepare_metadata_for_build_wheel
        metadata = make_metadata(module, ini_info)
      File "/private/var/folders/yd/lvv_242j0_j38xt5p54y2q8w0000gn/T/pip-build-env-ys8mlda8/overlay/lib/python3.7/site-packages/flit_core/common.py", line 392, in make_metadata
        md_dict.update(get_info_from_module(module, ini_info.dynamic_metadata))
      File "/private/var/folders/yd/lvv_242j0_j38xt5p54y2q8w0000gn/T/pip-build-env-ys8mlda8/overlay/lib/python3.7/site-packages/flit_core/common.py", line 189, in get_info_from_module
        docstring, version = get_docstring_and_version_via_import(target)
      File "/private/var/folders/yd/lvv_242j0_j38xt5p54y2q8w0000gn/T/pip-build-env-ys8mlda8/overlay/lib/python3.7/site-packages/flit_core/common.py", line 165, in get_docstring_and_version_via_import
        m = sl.load_module()
      File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
      File "<frozen importlib._bootstrap_external>", line 907, in load_module
      File "<frozen importlib._bootstrap_external>", line 732, in load_module
      File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
      File "<frozen importlib._bootstrap>", line 696, in _load
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/private/var/folders/yd/lvv_242j0_j38xt5p54y2q8w0000gn/T/pip-req-build-zoh5p0rp/Scribe/__init__.py", line 13, in <module>
        from . import pl
      File "/private/var/folders/yd/lvv_242j0_j38xt5p54y2q8w0000gn/T/pip-req-build-zoh5p0rp/Scribe/pl.py", line 4, in <module>
        from Scribe.plot import *
    ModuleNotFoundError: No module named 'Scribe'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/yd/lvv_242j0_j38xt5p54y2q8w0000gn/T/tmpc8h1o041 Check the logs for full command output.

**Comment by khanthanan** [comment]
@samIndeed, 
did you manage to fix this issue? I'm also having the same issue.

**Comment by zsteve** [comment]
I'm having the same issue here. Any input @Xiaojieqiu ?

**Comment by astrophys** [comment]
I'm having a similar issue.

**Comment by BW15061999** [comment]
I installed successfully with `python setup.py install`

**Comment by buttercutter** [comment]
When I run `python setup.py install --user` , it gave me some package dependency error : `error: numpy 1.24.2 is installed but numpy<1.24,>=1.18 is required by {'numba'}
`

**Comment by danbiv** [comment]
Fixed by deleting the word Scribe from the file pl.py so the line is:

from .plot import *
